### ISSUE TITLE
Unable to update anymore

### ISSUE THREAD

**Issue by Sush-ruta** [Volcomix/500wallpaper#46]
Whenever I do `npm -g update` I get this:
```
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name ".500wallpaper-Ck5aX5kX": name cannot start with a period
```
Seems to have begun since the  last update.

**Comment by Volcomix** [comment]
Seems very strange and can't manage to reproduce it. I Tried:
* `npm -g install 500wallpaper`
* `npm -g install 500wallpaper@1.1.17` then `npm -g update`
Without any error.

Could you try `npm -g uninstall 500wallpaper` then `npm -g install 500wallpaper`?
If you still get an error, could you please share the output of `npm -g list`?

**Comment by Sush-ruta** [comment]
Here is the output to all the commands:

![Screenshot at 17-01-48](https://user-images.githubusercontent.com/90390814/155311726-d501411c-34bc-422b-aaec-c292143baa69.png)

**Comment by Volcomix** [comment]
I would suspect this to be related to an issue in NPM, found 2 open issues with very similar symptoms:
* https://github.com/npm/cli/issues/4096
* https://github.com/npm/cli/issues/4455

Looks like a workaround would be to run `rm -rf /home/sushruta/.npm-global/lib/node_modules/500wallpaper` (and maybe the same with `.500wallpaper-Ck5aX5kX` if it exists?).

**Comment by Sush-ruta** [comment]
Thank you for the detailed solution. It worked! And thank you for 500wallpaper too. :)
